// src/components/ajo-custom/primary-button.tsx
import React from "react";

const PrimaryButton = () => {
  return (
    <div>
      <div className="w-44 h-96 px-5 py-6 rounded border border-purple-500 flex-col justify-start items-start gap-6 inline-flex">
        <PbL />
        <PbL2 />
        <Varient_6 />
        <PbM />
        <Varient_5 />
        <PbS />
      </div>
    </div>
  );
};

export default PrimaryButton;

// src/components/ajo-custom/PrimaryButton.svelte
<script>
	import PbL from "./PB_L.svelte";
	import PbL2 from "./PB_L2.svelte";
	import PbM from "./PB_M.svelte";
	import PbS from "./PB_S.svelte";
	import Varient_5 from "./Varient_5.svelte";
	import Varient_6 from "./Varient_6.svelte";

</script>
<div class="w-44 h-96 px-5 py-6 rounded border border-purple-500 flex-col justify-start items-start gap-6 inline-flex">
    <PbL/>
    <PbL2/>
    <Varient_6/>
    <PbM/>
    <Varient_5/>
    <PbS/>
  </div>
