// src/components/ajo-custom/reactions.tsx
import { Share } from "next/font/google";
import React from "react";
import BookMark from "./book-mark";
import NotBookmark from "./not-bookmark";

const reactions = () => {
  return (
    <div>
      <div className="w-80 h-8 py-1 justify-start items-center gap-7 flex flex-row">
        <Unliked />
        <Love />
        <Comment />
        <Share />
        <BookMark />
        <NotBookmark />
      </div>
    </div>
  );
};

export default reactions;

// src/components/ajo-custom/reactions.svelte
<script>
	import NotBookmark from "./NotBookmark.svelte";
import Unliked from "./Unliked.svelte";
	import BookMark from "./bookMark.svelte";
import Comment from "./comment.svelte";
import Love from "./liked.svelte";
	import Share from "./share.svelte";

</script>
<div class="w-80 h-8 py-1 justify-start items-center gap-7 flex flex-row">
   <Unliked/>
    <Love/>
    <Comment/>
    <Share/>    
    <BookMark/>
    <NotBookmark/>
  </div>
