// src/components/ajo-custom/Table.svelte
<div class="w-96 h-96 relative">
	<div class="w-96 h-96 left-0 top-0 absolute">
		<div class="w-96 h-96 left-0 top-0 absolute bg-white rounded-lg shadow" />
		<div class="w-96 h-20 left-0 top-[61px] absolute bg-white" />
		<div class="w-96 h-12 left-[45px] top-[78px] absolute">
			<div
				class="left-[855px] top-[14px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
			>
				Admin
			</div>
			<div
				class="w-14 h-6 px-2.5 py-0.5 left-[655px] top-[10px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex"
			>
				<div class="text-green-700 text-xs font-medium font-['Inter'] leading-tight">Active</div>
			</div>
			<div
				class="w-56 h-12 left-[355px] top-0 absolute flex-col justify-start items-start gap-0.5 inline-flex"
			>
				<div class="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
					Multidisciplinary Web Entrepreneur
				</div>
				<div class="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">Developer</div>
			</div>
			<div class="w-56 h-11 left-0 top-[1px] absolute justify-start items-center gap-4 inline-flex">
				<img class="w-11 h-11 rounded-full" src="https://via.placeholder.com/45x45" />
				<div class="flex-col justify-start items-start inline-flex">
					<div class="text-gray-900 text-sm font-medium font-['Inter'] leading-snug">
						Musharof Chowdhury
					</div>
					<div class="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
						musharof@example.com
					</div>
				</div>
			</div>
			<div
				class="w-16 h-8 px-5 py-1 left-[1010px] top-[7px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex"
			>
				<div class="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal">
					Edit
				</div>
			</div>
		</div>
		<div class="w-96 h-20 left-0 top-[142px] absolute bg-white" />
		<div class="w-96 h-20 left-0 top-[223px] absolute bg-white" />
		<div class="w-96 h-20 left-0 top-[304px] absolute bg-white" />
		<div class="w-96 h-20 left-0 top-[385px] absolute bg-white" />
		<div class="w-96 h-20 left-0 top-[466px] absolute bg-white rounded-bl-lg rounded-br-lg" />
		<div class="w-96 h-11 left-[45px] top-[160px] absolute">
			<div
				class="w-16 h-8 px-5 py-1 left-[1010px] top-[6px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex"
			>
				<div class="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal">
					Edit
				</div>
			</div>
			<div class="w-64 h-11 left-0 top-0 absolute">
				<img
					class="w-11 h-11 left-0 top-0 absolute rounded-full"
					src="https://via.placeholder.com/45x45"
				/>
				<div class="w-48 h-10 left-[63px] top-[3px] absolute">
					<div
						class="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug"
					>
						Nenifer Lofess
					</div>
					<div
						class="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
					>
						loffes.cooper@example.com
					</div>
				</div>
			</div>
			<div
				class="left-[855px] top-[13px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
			>
				Owner
			</div>
			<div class="w-96 h-11 left-[355px] top-[1px] absolute">
				<div
					class="left-0 top-0 absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
				>
					Regional Paradigm Technician
				</div>
				<div
					class="w-14 h-6 px-2.5 py-0.5 left-[300px] top-[8px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex"
				>
					<div class="text-green-700 text-xs font-medium font-['Inter'] leading-tight">Active</div>
				</div>
				<div
					class="left-0 top-[23px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
				>
					Optimization
				</div>
			</div>
		</div>
		<div class="w-96 h-20 left-0 top-[223px] absolute">
			<div class="w-96 h-20 left-0 top-0 absolute bg-white" />
			<div class="w-96 h-11 left-[45px] top-[18px] absolute">
				<div
					class="w-16 h-8 px-5 py-1 left-[1010px] top-[6px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex"
				>
					<div
						class="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal"
					>
						Edit
					</div>
				</div>
				<div
					class="left-[855px] top-[13px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
				>
					Member
				</div>
				<div class="w-96 h-11 left-[355px] top-[1px] absolute">
					<div
						class="left-0 top-0 absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
					>
						Regional Paradigm Technician
					</div>
					<div
						class="w-14 h-6 px-2.5 py-0.5 left-[300px] top-[8px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex"
					>
						<div class="text-green-700 text-xs font-medium font-['Inter'] leading-tight">
							Active
						</div>
					</div>
					<div
						class="left-0 top-[23px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
					>
						Optimization
					</div>
				</div>
				<div class="w-60 h-11 left-0 top-0 absolute">
					<img
						class="w-11 h-11 left-0 top-0 absolute rounded-full"
						src="https://via.placeholder.com/45x45"
					/>
					<div class="w-44 h-10 left-[63px] top-[3px] absolute">
						<div
							class="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug"
						>
							Jhon Smith
						</div>
						<div
							class="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
						>
							jhon.smith@example.com
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="w-96 h-20 left-0 top-[304px] absolute">
			<div class="w-96 h-20 left-0 top-0 absolute bg-white" />
			<div class="w-96 h-11 left-[45px] top-[18px] absolute">
				<div
					class="w-16 h-8 px-5 py-1 left-[1010px] top-[6px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex"
				>
					<div
						class="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal"
					>
						Edit
					</div>
				</div>
				<div class="w-60 h-11 left-0 top-0 absolute">
					<img
						class="w-11 h-11 left-0 top-0 absolute rounded-full"
						src="https://via.placeholder.com/45x45"
					/>
					<div class="w-44 h-10 left-[63px] top-[3px] absolute">
						<div
							class="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug"
						>
							Sulium Keliym
						</div>
						<div
							class="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
						>
							suliym.info@example.com
						</div>
					</div>
				</div>
				<div
					class="left-[855px] top-[13px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
				>
					Admin
				</div>
				<div class="w-96 h-11 left-[355px] top-[1px] absolute">
					<div
						class="left-0 top-0 absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
					>
						Lead Implementation Liaison
					</div>
					<div
						class="left-0 top-[23px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
					>
						Mobility
					</div>
					<div
						class="w-14 h-6 px-2.5 py-0.5 left-[300px] top-[8px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex"
					>
						<div class="text-green-700 text-xs font-medium font-['Inter'] leading-tight">
							Active
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="w-96 h-20 left-0 top-[385px] absolute">
			<div class="w-96 h-20 left-0 top-0 absolute bg-white" />
			<div class="w-96 h-12 left-[45px] top-[17px] absolute">
				<div
					class="w-16 h-8 px-5 py-1 left-[1010px] top-[7px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex"
				>
					<div
						class="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal"
					>
						Edit
					</div>
				</div>
				<div class="w-60 h-11 left-0 top-[1px] absolute">
					<img
						class="w-11 h-11 left-0 top-0 absolute rounded-full"
						src="https://via.placeholder.com/45x45"
					/>
					<div class="w-44 h-10 left-[63px] top-[3px] absolute">
						<div
							class="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug"
						>
							Alex Semuyel
						</div>
						<div
							class="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
						>
							alex.semuel@example.com
						</div>
					</div>
				</div>
				<div
					class="left-[855px] top-[14px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
				>
					Admin
				</div>
				<div class="w-96 h-12 left-[355px] top-0 absolute">
					<div
						class="w-20 h-6 px-2.5 py-0.5 left-[300px] top-[10px] absolute bg-rose-100 rounded-3xl justify-center items-center gap-px inline-flex"
					>
						<div class="text-red-600 text-xs font-medium font-['Inter'] leading-tight">
							Deactivate
						</div>
					</div>
					<div
						class="w-36 h-12 left-0 top-0 absolute flex-col justify-start items-start gap-0.5 inline-flex"
					>
						<div class="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
							Applications Engineer
						</div>
						<div class="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
							Security
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="w-96 h-20 left-0 top-[466px] absolute">
			<div class="w-96 h-20 left-0 top-0 absolute bg-white rounded-bl-lg rounded-br-lg" />
			<div class="w-96 h-12 left-[45px] top-[17px] absolute">
				<div
					class="w-16 h-8 px-5 py-1 left-[1010px] top-[7px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex"
				>
					<div
						class="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal"
					>
						Edit
					</div>
				</div>
				<div class="w-52 h-11 left-0 top-[1px] absolute">
					<img
						class="w-11 h-11 left-0 top-0 absolute rounded-full"
						src="https://via.placeholder.com/45x45"
					/>
					<div class="w-36 h-10 left-[63px] top-[3px] absolute">
						<div
							class="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug"
						>
							Humil Limition
						</div>
						<div
							class="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
						>
							limition@example.com
						</div>
					</div>
				</div>
				<div
					class="left-[855px] top-[14px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug"
				>
					Member
				</div>
				<div
					class="w-14 h-6 px-2.5 py-0.5 left-[655px] top-[10px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex"
				>
					<div class="text-green-700 text-xs font-medium font-['Inter'] leading-tight">Active</div>
				</div>
				<div
					class="w-48 h-12 left-[355px] top-0 absolute flex-col justify-start items-start gap-0.5 inline-flex"
				>
					<div class="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
						Regional Paradigm Technician
					</div>
					<div class="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
						Optimization
					</div>
				</div>
			</div>
		</div>
		<div class="w-96 h-14 left-0 top-0 absolute bg-gray-50 rounded-tl-lg rounded-tr-lg" />
		<div class="w-96 h-px left-0 top-[61px] absolute border border-zinc-100" />
		<div
			class="left-[45px] top-[17px] absolute text-gray-900 text-base font-medium font-['Inter'] leading-relaxed"
		>
			NAME
		</div>
		<div
			class="left-[400px] top-[17px] absolute text-gray-900 text-base font-medium font-['Inter'] leading-relaxed"
		>
			TITLE
		</div>
		<div
			class="left-[700px] top-[17px] absolute text-gray-900 text-base font-medium font-['Inter'] leading-relaxed"
		>
			STATUS
		</div>
		<div
			class="left-[900px] top-[17px] absolute text-gray-900 text-base font-medium font-['Inter'] leading-relaxed"
		>
			ROLE
		</div>
	</div>
	<div class="w-96 h-px left-0 top-[142px] absolute border border-zinc-100" />
	<div class="w-96 h-px left-0 top-[223px] absolute border border-zinc-100" />
	<div class="w-96 h-px left-0 top-[304px] absolute border border-zinc-100" />
	<div class="w-96 h-px left-0 top-[385px] absolute border border-zinc-100" />
	<div class="w-96 h-px left-0 top-[466px] absolute border border-zinc-100" />
</div>

// src/components/ajo-custom/Table.tsx
import React from "react";

const Table = () => {
  return (
    <div>
      <div className="w-96 h-96 relative">
        <div className="w-96 h-96 left-0 top-0 absolute">
          <div className="w-96 h-96 left-0 top-0 absolute bg-white rounded-lg shadow" />
          <div className="w-96 h-20 left-0 top-[61px] absolute bg-white" />
          <div className="w-96 h-12 left-[45px] top-[78px] absolute">
            <div className="left-[855px] top-[14px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
              Admin
            </div>
            <div className="w-14 h-6 px-2.5 py-0.5 left-[655px] top-[10px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex">
              <div className="text-green-700 text-xs font-medium font-['Inter'] leading-tight">
                Active
              </div>
            </div>
            <div className="w-56 h-12 left-[355px] top-0 absolute flex-col justify-start items-start gap-0.5 inline-flex">
              <div className="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                Multidisciplinary Web Entrepreneur
              </div>
              <div className="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                Developer
              </div>
            </div>
            <div className="w-56 h-11 left-0 top-[1px] absolute justify-start items-center gap-4 inline-flex">
              <img
                className="w-11 h-11 rounded-full"
                src="https://via.placeholder.com/45x45"
              />
              <div className="flex-col justify-start items-start inline-flex">
                <div className="text-gray-900 text-sm font-medium font-['Inter'] leading-snug">
                  Musharof Chowdhury
                </div>
                <div className="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                  musharof@example.com
                </div>
              </div>
            </div>
            <div className="w-16 h-8 px-5 py-1 left-[1010px] top-[7px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex">
              <div className="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal">
                Edit
              </div>
            </div>
          </div>
          <div className="w-96 h-20 left-0 top-[142px] absolute bg-white" />
          <div className="w-96 h-20 left-0 top-[223px] absolute bg-white" />
          <div className="w-96 h-20 left-0 top-[304px] absolute bg-white" />
          <div className="w-96 h-20 left-0 top-[385px] absolute bg-white" />
          <div className="w-96 h-20 left-0 top-[466px] absolute bg-white rounded-bl-lg rounded-br-lg" />
          <div className="w-96 h-11 left-[45px] top-[160px] absolute">
            <div className="w-16 h-8 px-5 py-1 left-[1010px] top-[6px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex">
              <div className="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal">
                Edit
              </div>
            </div>
            <div className="w-64 h-11 left-0 top-0 absolute">
              <img
                className="w-11 h-11 left-0 top-0 absolute rounded-full"
                src="https://via.placeholder.com/45x45"
              />
              <div className="w-48 h-10 left-[63px] top-[3px] absolute">
                <div className="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug">
                  Nenifer Lofess
                </div>
                <div className="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                  loffes.cooper@example.com
                </div>
              </div>
            </div>
            <div className="left-[855px] top-[13px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
              Owner
            </div>
            <div className="w-96 h-11 left-[355px] top-[1px] absolute">
              <div className="left-0 top-0 absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                Regional Paradigm Technician
              </div>
              <div className="w-14 h-6 px-2.5 py-0.5 left-[300px] top-[8px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex">
                <div className="text-green-700 text-xs font-medium font-['Inter'] leading-tight">
                  Active
                </div>
              </div>
              <div className="left-0 top-[23px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                Optimization
              </div>
            </div>
          </div>
          <div className="w-96 h-20 left-0 top-[223px] absolute">
            <div className="w-96 h-20 left-0 top-0 absolute bg-white" />
            <div className="w-96 h-11 left-[45px] top-[18px] absolute">
              <div className="w-16 h-8 px-5 py-1 left-[1010px] top-[6px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex">
                <div className="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal">
                  Edit
                </div>
              </div>
              <div className="left-[855px] top-[13px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                Member
              </div>
              <div className="w-96 h-11 left-[355px] top-[1px] absolute">
                <div className="left-0 top-0 absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                  Regional Paradigm Technician
                </div>
                <div className="w-14 h-6 px-2.5 py-0.5 left-[300px] top-[8px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex">
                  <div className="text-green-700 text-xs font-medium font-['Inter'] leading-tight">
                    Active
                  </div>
                </div>
                <div className="left-0 top-[23px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                  Optimization
                </div>
              </div>
              <div className="w-60 h-11 left-0 top-0 absolute">
                <img
                  className="w-11 h-11 left-0 top-0 absolute rounded-full"
                  src="https://via.placeholder.com/45x45"
                />
                <div className="w-44 h-10 left-[63px] top-[3px] absolute">
                  <div className="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug">
                    Jhon Smith
                  </div>
                  <div className="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                    jhon.smith@example.com
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="w-96 h-20 left-0 top-[304px] absolute">
            <div className="w-96 h-20 left-0 top-0 absolute bg-white" />
            <div className="w-96 h-11 left-[45px] top-[18px] absolute">
              <div className="w-16 h-8 px-5 py-1 left-[1010px] top-[6px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex">
                <div className="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal">
                  Edit
                </div>
              </div>
              <div className="w-60 h-11 left-0 top-0 absolute">
                <img
                  className="w-11 h-11 left-0 top-0 absolute rounded-full"
                  src="https://via.placeholder.com/45x45"
                />
                <div className="w-44 h-10 left-[63px] top-[3px] absolute">
                  <div className="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug">
                    Sulium Keliym
                  </div>
                  <div className="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                    suliym.info@example.com
                  </div>
                </div>
              </div>
              <div className="left-[855px] top-[13px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                Admin
              </div>
              <div className="w-96 h-11 left-[355px] top-[1px] absolute">
                <div className="left-0 top-0 absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                  Lead Implementation Liaison
                </div>
                <div className="left-0 top-[23px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                  Mobility
                </div>
                <div className="w-14 h-6 px-2.5 py-0.5 left-[300px] top-[8px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex">
                  <div className="text-green-700 text-xs font-medium font-['Inter'] leading-tight">
                    Active
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="w-96 h-20 left-0 top-[385px] absolute">
            <div className="w-96 h-20 left-0 top-0 absolute bg-white" />
            <div className="w-96 h-12 left-[45px] top-[17px] absolute">
              <div className="w-16 h-8 px-5 py-1 left-[1010px] top-[7px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex">
                <div className="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal">
                  Edit
                </div>
              </div>
              <div className="w-60 h-11 left-0 top-[1px] absolute">
                <img
                  className="w-11 h-11 left-0 top-0 absolute rounded-full"
                  src="https://via.placeholder.com/45x45"
                />
                <div className="w-44 h-10 left-[63px] top-[3px] absolute">
                  <div className="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug">
                    Alex Semuyel
                  </div>
                  <div className="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                    alex.semuel@example.com
                  </div>
                </div>
              </div>
              <div className="left-[855px] top-[14px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                Admin
              </div>
              <div className="w-96 h-12 left-[355px] top-0 absolute">
                <div className="w-20 h-6 px-2.5 py-0.5 left-[300px] top-[10px] absolute bg-rose-100 rounded-3xl justify-center items-center gap-px inline-flex">
                  <div className="text-red-600 text-xs font-medium font-['Inter'] leading-tight">
                    Deactivate
                  </div>
                </div>
                <div className="w-36 h-12 left-0 top-0 absolute flex-col justify-start items-start gap-0.5 inline-flex">
                  <div className="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                    Applications Engineer
                  </div>
                  <div className="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                    Security
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="w-96 h-20 left-0 top-[466px] absolute">
            <div className="w-96 h-20 left-0 top-0 absolute bg-white rounded-bl-lg rounded-br-lg" />
            <div className="w-96 h-12 left-[45px] top-[17px] absolute">
              <div className="w-16 h-8 px-5 py-1 left-[1010px] top-[7px] absolute bg-white rounded-3xl border border-blue-600 justify-center items-center gap-2.5 inline-flex">
                <div className="text-center text-blue-600 text-base font-medium font-['Inter'] leading-normal">
                  Edit
                </div>
              </div>
              <div className="w-52 h-11 left-0 top-[1px] absolute">
                <img
                  className="w-11 h-11 left-0 top-0 absolute rounded-full"
                  src="https://via.placeholder.com/45x45"
                />
                <div className="w-36 h-10 left-[63px] top-[3px] absolute">
                  <div className="left-0 top-0 absolute text-gray-900 text-sm font-medium font-['Inter'] leading-snug">
                    Humil Limition
                  </div>
                  <div className="left-0 top-[19px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                    limition@example.com
                  </div>
                </div>
              </div>
              <div className="left-[855px] top-[14px] absolute text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                Member
              </div>
              <div className="w-14 h-6 px-2.5 py-0.5 left-[655px] top-[10px] absolute bg-green-100 rounded-3xl justify-center items-center gap-px inline-flex">
                <div className="text-green-700 text-xs font-medium font-['Inter'] leading-tight">
                  Active
                </div>
              </div>
              <div className="w-48 h-12 left-[355px] top-0 absolute flex-col justify-start items-start gap-0.5 inline-flex">
                <div className="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                  Regional Paradigm Technician
                </div>
                <div className="text-gray-500 text-sm font-normal font-['Inter'] leading-snug">
                  Optimization
                </div>
              </div>
            </div>
          </div>
          <div className="w-96 h-14 left-0 top-0 absolute bg-gray-50 rounded-tl-lg rounded-tr-lg" />
          <div className="w-96 h-px left-0 top-[61px] absolute border border-zinc-100" />
          <div className="left-[45px] top-[17px] absolute text-gray-900 text-base font-medium font-['Inter'] leading-relaxed">
            NAME
          </div>
          <div className="left-[400px] top-[17px] absolute text-gray-900 text-base font-medium font-['Inter'] leading-relaxed">
            TITLE
          </div>
          <div className="left-[700px] top-[17px] absolute text-gray-900 text-base font-medium font-['Inter'] leading-relaxed">
            STATUS
          </div>
          <div className="left-[900px] top-[17px] absolute text-gray-900 text-base font-medium font-['Inter'] leading-relaxed">
            ROLE
          </div>
        </div>
        <div className="w-96 h-px left-0 top-[142px] absolute border border-zinc-100" />
        <div className="w-96 h-px left-0 top-[223px] absolute border border-zinc-100" />
        <div className="w-96 h-px left-0 top-[304px] absolute border border-zinc-100" />
        <div className="w-96 h-px left-0 top-[385px] absolute border border-zinc-100" />
        <div className="w-96 h-px left-0 top-[466px] absolute border border-zinc-100" />
      </div>
    </div>
  );
};

export default Table;
